# Generated by Django 5.2.4 on 2025-07-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
